# Generated by Django 4.2 on 2023-05-23 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessRoom',
            fields=[
                ('room_name', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('player_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChessTournament',
            fields=[
                ('tournament_name', models.CharField(default='aaaaaa', max_length=6, primary_key=True, serialize=False)),
                ('num_total_players', models.PositiveIntegerField(default=4)),
                ('current_num_players', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChessTrackPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('winner', 'winner'), ('loser', 'loser'), ('draw', 'draw')], max_length=6)),
                ('score', models.IntegerField()),
                ('type', models.CharField(choices=[('public', 'public'), ('tournament', 'tournament')], default='public', max_length=10)),
                ('opponent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChessRoomBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=70)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.chessroom')),
            ],
        ),
        migrations.CreateModel(
            name='ChessTournamentLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chesstournament')),
            ],
            options={
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='ChessRoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_orientation', models.CharField(default='black', max_length=5)),
                ('player_turn', models.BooleanField(default=False)),
                ('player_timer_in_seconds', models.IntegerField(default=300)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chessroom')),
            ],
            options={
                'unique_together': {('room', 'player')},
            },
        ),
    ]
