# Generated by Django 4.2 on 2023-05-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessroom',
            name='player_count',
        ),
        migrations.RemoveField(
            model_name='chesstournament',
            name='current_num_players',
        ),
    ]
