# Generated by Django 4.2 on 2023-05-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_chessroom_room_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesstournament',
            name='num_total_players',
        ),
        migrations.AddField(
            model_name='chesstournamentlobby',
            name='num_total_players',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='chesstournamentlobby',
            name='turno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
