# Generated by Django 4.2 on 2023-05-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_chesstournament_num_total_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesstournamentlobby',
            name='num_total_players',
        ),
        migrations.RemoveField(
            model_name='chesstournamentlobby',
            name='turno',
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='num_total_players',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
