# Generated by Django 4.2 on 2023-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_chesstournamentdraw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chesstournamentlobby',
            old_name='is_qualified',
            new_name='player_is_qualified',
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='tournament_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chesstournament',
            name='tournament_status',
            field=models.CharField(choices=[('waiting-for-players', 'waiting-for-players'), ('start-draws', 'start-draws'), ('players-in-game', 'players-in-game'), ('tournament-closed', 'tournament-closed')], default='waiting-for-players', max_length=20),
        ),
        migrations.AddField(
            model_name='chesstournamentlobby',
            name='player_status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('in-game', 'in-game')], default='waiting', max_length=20),
        ),
    ]
