# Generated by Django 4.2 on 2023-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_chesstournament_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesstournamentlobby',
            name='player_status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('IN_GAME', 'IN_GAME')], default='WAITING', max_length=20),
        ),
    ]
